version: '3.8'

services:

  # =====================
  # PostgreSQL Database
  # =====================
  postgres:
    image: postgres:16
    container_name: grocery-postgres
    environment:
      POSTGRES_DB: ecommercedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Disney@1701
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =====================
  # Spring Boot App
  # =====================
  app:
    build: .
    container_name: grocery-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommercedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Disney@1701
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
