--
-- PostgreSQL database dump
--



-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Cart; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Cart" (
    id bigint NOT NULL,
    userid integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp(6) without time zone,
    user_id integer
);


--
-- Name: Cart_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Cart" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cart_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Categories" (
    id bigint NOT NULL,
    name character varying(255),
    description character varying(255)
);


--
-- Name: Categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Categories" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Orders" (
    id bigint NOT NULL,
    user_id integer,
    total_amount numeric(38,2),
    status character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    channel character varying(255),
    kitchen_status character varying(255),
    customer_notes text,
    kitchen_notes text,
    approval_notes text,
    approval_status character varying(255),
    approved_at timestamp(6) without time zone,
    requires_approval boolean,
    approved_by_user_id integer
);


--
-- Name: Orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Orders" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Orders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Product_Available; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Product_Available" (
    id bigint NOT NULL,
    name character varying(255),
    description character varying(255),
    price numeric(38,2),
    stock integer,
    category_id bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by_userid integer,
    image_url character varying(255)
);


--
-- Name: Product_Available_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Product_Available" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Product_Available_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Product_Images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Product_Images" (
    id bigint NOT NULL,
    product_id bigint,
    image_url character varying(255)
);


--
-- Name: Product_Images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Product_Images" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Product_Images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Products" (
    id bigint NOT NULL,
    name character varying(255),
    description character varying(255),
    price numeric(38,2),
    stock integer,
    category_id bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by_userid integer,
    supported_flours character varying(255),
    supported_sweeteners character varying(255),
    CONSTRAINT products_price_nonneg CHECK ((price >= (0)::numeric)),
    CONSTRAINT products_stock_nonneg CHECK ((stock >= 0))
);


--
-- Name: Products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Products" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Role" (
    id integer NOT NULL,
    "fullName" character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    department character varying(255)
);


--
-- Name: Role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Role_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Role_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Role_id_seq" OWNED BY public."Role".id;


--
-- Name: User; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."User" (
    userid integer CONSTRAINT "User_UserId_not_null" NOT NULL,
    name character varying(255),
    email character varying(255),
    password character varying(255),
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: User_UserId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."User_UserId_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: User_UserId_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."User_UserId_seq" OWNED BY public."User".userid;


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    cart_id bigint,
    product_id bigint,
    quantity integer,
    customization text,
    flour_type character varying(255),
    sweetener_percent integer,
    sweetener_type character varying(255),
    CONSTRAINT cart_items_flour_type_chk CHECK (((flour_type IS NULL) OR ((flour_type)::text = ANY ((ARRAY['FINGER_MILLET'::character varying, 'BAJRA_MILLET'::character varying, 'LITTLE_MILLET'::character varying, 'SORGHUM'::character varying, 'WHOLE_WHEAT'::character varying, 'ALL_PURPOSE'::character varying])::text[])))),
    CONSTRAINT cart_items_qty_positive CHECK ((quantity > 0)),
    CONSTRAINT cart_items_sweetener_pct_range CHECK (((sweetener_percent IS NULL) OR ((sweetener_percent >= 0) AND (sweetener_percent <= 100)))),
    CONSTRAINT cart_items_sweetener_type_chk CHECK (((sweetener_type IS NULL) OR ((sweetener_type)::text = ANY ((ARRAY['CANE_SUGAR'::character varying, 'BROWN_SUGAR'::character varying, 'MAPLE_SYRUP'::character varying, 'JAGGERY'::character varying, 'HONEY'::character varying])::text[]))))
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_stock (
    id bigint NOT NULL,
    prepared_count integer,
    stock_date date,
    target_count integer,
    product_id bigint
);


--
-- Name: daily_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delivery_issues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.delivery_issues (
    id bigint NOT NULL,
    description text,
    issue_type character varying(255),
    reported_at timestamp(6) without time zone,
    resolved_at timestamp(6) without time zone,
    driver_user_id integer,
    trip_id bigint
);


--
-- Name: delivery_issues_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.delivery_issues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_issues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delivery_trips; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.delivery_trips (
    id bigint NOT NULL,
    cod_amount numeric(38,2),
    cod_collected_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    delivered_at timestamp(6) without time zone,
    distance_km numeric(38,2),
    failed_at timestamp(6) without time zone,
    failure_reason character varying(255),
    notes text,
    otp_code character varying(255),
    out_at timestamp(6) without time zone,
    photo_proof_url text,
    picked_up_at timestamp(6) without time zone,
    status character varying(255),
    tip_amount numeric(38,2),
    updated_at timestamp(6) without time zone,
    driver_user_id integer,
    order_id bigint
);


--
-- Name: delivery_trips_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.delivery_trips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_trips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: discount_campaigns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discount_campaigns (
    id bigint NOT NULL,
    category_filter character varying(255),
    created_at timestamp(6) without time zone,
    decided_at timestamp(6) without time zone,
    decision_notes text,
    discount_percent numeric(38,2),
    ends_on date,
    name character varying(255),
    starts_on date,
    status character varying(255),
    decided_by_user_id integer,
    proposed_by_user_id integer
);


--
-- Name: discount_campaigns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.discount_campaigns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discount_campaigns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    order_id bigint,
    product_id bigint,
    quantity integer,
    price numeric(38,2),
    customization text,
    flour_type character varying(255),
    sweetener_percent integer,
    sweetener_type character varying(255)
);


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    order_id bigint,
    payment_method character varying(255),
    status character varying(255),
    amount numeric(38,2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refund_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refund_requests (
    id bigint NOT NULL,
    amount numeric(38,2),
    created_at timestamp(6) without time zone,
    decided_at timestamp(6) without time zone,
    decision_notes text,
    reason character varying(255),
    request_type character varying(255),
    status character varying(255),
    decided_by_user_id integer,
    order_id bigint,
    raised_by_user_id integer
);


--
-- Name: refund_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refund_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refund_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipping_addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipping_addresses (
    id bigint NOT NULL,
    address_type character varying(255),
    city character varying(255),
    country character varying(255),
    created_at timestamp(6) without time zone,
    full_name character varying(255),
    instructions text,
    landmark character varying(255),
    line1 character varying(255),
    line2 character varying(255),
    phone character varying(255),
    pincode character varying(255),
    state character varying(255),
    order_id bigint,
    user_id integer
);


--
-- Name: shipping_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipping_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipping_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supplies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supplies (
    id bigint NOT NULL,
    category character varying(255),
    current_stock numeric(12,3),
    name character varying(255) NOT NULL,
    notes text,
    threshold numeric(12,3),
    unit character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    order_status character varying(255),
    requested_at timestamp(6) without time zone,
    in_stock numeric(12,3),
    requested_qty numeric(12,3),
    requested_by_team character varying(255)
);


--
-- Name: supplies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.supplies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasks (
    id bigint NOT NULL,
    assigned_department character varying(255),
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    description text,
    due_date date,
    priority character varying(255),
    related_order_id bigint,
    resolution_notes text,
    status character varying(255),
    title character varying(255),
    updated_at timestamp(6) without time zone,
    assigned_user_id integer,
    completed_by_user_id integer,
    created_by_user_id integer
);


--
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: userRole; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."userRole" (
    userroleid integer NOT NULL,
    userid integer NOT NULL,
    roleid integer NOT NULL
);


--
-- Name: userRole_userroleid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."userRole_userroleid_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: userRole_userroleid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."userRole_userroleid_seq" OWNED BY public."userRole".userroleid;


--
-- Name: Role id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Role" ALTER COLUMN id SET DEFAULT nextval('public."Role_id_seq"'::regclass);


--
-- Name: User userid; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User" ALTER COLUMN userid SET DEFAULT nextval('public."User_UserId_seq"'::regclass);


--
-- Name: userRole userroleid; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userRole" ALTER COLUMN userroleid SET DEFAULT nextval('public."userRole_userroleid_seq"'::regclass);


--
-- Name: Cart Cart_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Cart"
    ADD CONSTRAINT "Cart_pkey" PRIMARY KEY (id);


--
-- Name: Categories Categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "Categories_pkey" PRIMARY KEY (id);


--
-- Name: Orders Orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "Orders_pkey" PRIMARY KEY (id);


--
-- Name: Product_Available Product_Available_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Product_Available"
    ADD CONSTRAINT "Product_Available_pkey" PRIMARY KEY (id);


--
-- Name: Product_Images Product_Images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Product_Images"
    ADD CONSTRAINT "Product_Images_pkey" PRIMARY KEY (id);


--
-- Name: Products Products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "Products_pkey" PRIMARY KEY (id);


--
-- Name: Role Role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Role"
    ADD CONSTRAINT "Role_pkey" PRIMARY KEY (id);


--
-- Name: User User_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY (userid);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: daily_stock daily_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_stock
    ADD CONSTRAINT daily_stock_pkey PRIMARY KEY (id);


--
-- Name: delivery_issues delivery_issues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_issues
    ADD CONSTRAINT delivery_issues_pkey PRIMARY KEY (id);


--
-- Name: delivery_trips delivery_trips_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_trips
    ADD CONSTRAINT delivery_trips_pkey PRIMARY KEY (id);


--
-- Name: discount_campaigns discount_campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discount_campaigns
    ADD CONSTRAINT discount_campaigns_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: refund_requests refund_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT refund_requests_pkey PRIMARY KEY (id);


--
-- Name: shipping_addresses shipping_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipping_addresses
    ADD CONSTRAINT shipping_addresses_pkey PRIMARY KEY (id);


--
-- Name: supplies supplies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplies
    ADD CONSTRAINT supplies_pkey PRIMARY KEY (id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: userRole userRole_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userRole"
    ADD CONSTRAINT "userRole_pkey" PRIMARY KEY (userroleid);


--
-- Name: idx_cart_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cart_user ON public."Cart" USING btree (user_id);


--
-- Name: idx_cartitems_cart; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cartitems_cart ON public.cart_items USING btree (cart_id);


--
-- Name: idx_products_cat; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_cat ON public."Products" USING btree (category_id);


--
-- Name: Cart Cart_userid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Cart"
    ADD CONSTRAINT "Cart_userid_fkey" FOREIGN KEY (userid) REFERENCES public."User"(userid);


--
-- Name: Orders Orders_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "Orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(userid);


--
-- Name: Product_Available Product_Available_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Product_Available"
    ADD CONSTRAINT "Product_Available_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public."Categories"(id);


--
-- Name: Product_Available Product_Available_created_by_userid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Product_Available"
    ADD CONSTRAINT "Product_Available_created_by_userid_fkey" FOREIGN KEY (created_by_userid) REFERENCES public."User"(userid);


--
-- Name: Product_Images Product_Images_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Product_Images"
    ADD CONSTRAINT "Product_Images_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public."Products"(id);


--
-- Name: Products Products_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "Products_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public."Categories"(id);


--
-- Name: Products Products_created_by_userid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "Products_created_by_userid_fkey" FOREIGN KEY (created_by_userid) REFERENCES public."User"(userid);


--
-- Name: cart_items cart_items_cart_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public."Cart"(id);


--
-- Name: cart_items cart_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public."Products"(id);


--
-- Name: delivery_issues fk62cq4vi0ns6ix8knfqsjiyekr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_issues
    ADD CONSTRAINT fk62cq4vi0ns6ix8knfqsjiyekr FOREIGN KEY (trip_id) REFERENCES public.delivery_trips(id);


--
-- Name: discount_campaigns fk73g99csulv5apybg5ys2g4tiv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discount_campaigns
    ADD CONSTRAINT fk73g99csulv5apybg5ys2g4tiv FOREIGN KEY (proposed_by_user_id) REFERENCES public."User"(userid);


--
-- Name: Cart fk7ddmp0d4btlrk115achfm62jr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Cart"
    ADD CONSTRAINT fk7ddmp0d4btlrk115achfm62jr FOREIGN KEY (user_id) REFERENCES public."User"(userid);


--
-- Name: refund_requests fk7hwa1l8j1o5phuqayh4vn1rjr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT fk7hwa1l8j1o5phuqayh4vn1rjr FOREIGN KEY (order_id) REFERENCES public."Orders"(id);


--
-- Name: delivery_issues fk8lo2bnossv43gtq5r7nvnumd4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_issues
    ADD CONSTRAINT fk8lo2bnossv43gtq5r7nvnumd4 FOREIGN KEY (driver_user_id) REFERENCES public."User"(userid);


--
-- Name: refund_requests fkhdwae546kl5miegdo56nib1j9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT fkhdwae546kl5miegdo56nib1j9 FOREIGN KEY (decided_by_user_id) REFERENCES public."User"(userid);


--
-- Name: tasks fkj2yx28u7mh7729gpgw3ocwn4j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fkj2yx28u7mh7729gpgw3ocwn4j FOREIGN KEY (created_by_user_id) REFERENCES public."User"(userid);


--
-- Name: daily_stock fkkpffm1g65ycgly3h0i115yem2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_stock
    ADD CONSTRAINT fkkpffm1g65ycgly3h0i115yem2 FOREIGN KEY (product_id) REFERENCES public."Products"(id);


--
-- Name: tasks fkm4hbgq8cnk5oitqrf81vvrdef; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fkm4hbgq8cnk5oitqrf81vvrdef FOREIGN KEY (completed_by_user_id) REFERENCES public."User"(userid);


--
-- Name: discount_campaigns fkmtno9lx2eht6aa42skgdrb5uj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discount_campaigns
    ADD CONSTRAINT fkmtno9lx2eht6aa42skgdrb5uj FOREIGN KEY (decided_by_user_id) REFERENCES public."User"(userid);


--
-- Name: delivery_trips fkmwt4gj413kgiv5nhqgqhrhbdc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_trips
    ADD CONSTRAINT fkmwt4gj413kgiv5nhqgqhrhbdc FOREIGN KEY (driver_user_id) REFERENCES public."User"(userid);


--
-- Name: refund_requests fkoxg2h2hbsmcije9jnx9o2o1ws; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refund_requests
    ADD CONSTRAINT fkoxg2h2hbsmcije9jnx9o2o1ws FOREIGN KEY (raised_by_user_id) REFERENCES public."User"(userid);


--
-- Name: tasks fkq7ae0ge09ksdnd6jscsl1losu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fkq7ae0ge09ksdnd6jscsl1losu FOREIGN KEY (assigned_user_id) REFERENCES public."User"(userid);


--
-- Name: shipping_addresses fkqecrt6voyyrmr636852eb21qw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipping_addresses
    ADD CONSTRAINT fkqecrt6voyyrmr636852eb21qw FOREIGN KEY (order_id) REFERENCES public."Orders"(id);


--
-- Name: delivery_trips fkqegswlhpp2qox7s3s60vpb0qs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_trips
    ADD CONSTRAINT fkqegswlhpp2qox7s3s60vpb0qs FOREIGN KEY (order_id) REFERENCES public."Orders"(id);


--
-- Name: shipping_addresses fks8ysmsceitn95v5s4wd87wigh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipping_addresses
    ADD CONSTRAINT fks8ysmsceitn95v5s4wd87wigh FOREIGN KEY (user_id) REFERENCES public."User"(userid);


--
-- Name: Orders fktbh2vusj5r5ipohl4nwwkrjfp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT fktbh2vusj5r5ipohl4nwwkrjfp FOREIGN KEY (approved_by_user_id) REFERENCES public."User"(userid);


--
-- Name: order_items order_items_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public."Orders"(id);


--
-- Name: order_items order_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public."Products"(id);


--
-- Name: payments payments_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public."Orders"(id);


--
-- Name: userRole userRole_roleid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userRole"
    ADD CONSTRAINT "userRole_roleid_fkey" FOREIGN KEY (roleid) REFERENCES public."Role"(id);


--
-- Name: userRole userRole_userid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."userRole"
    ADD CONSTRAINT "userRole_userid_fkey" FOREIGN KEY (userid) REFERENCES public."User"(userid);


--
-- PostgreSQL database dump complete
--



